language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - python --version
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -r requirements.txt

env:
  - CODECOV_TOKEN=4f9eafa3-0ca3-48e4-9841-8fb25ff5d7c6

script:
  - pytest --verbose --color=yes phages2050
after_success:
  - codecov
